### ISSUE TITLE
package.json for osx issue

### ISSUE THREAD

**Issue by 10der** [dibyendumajumdar/ravi-vscode-debugger#2]
please fix this line
was:
"osx": {
					"program": "/bin/osx/ravidebug"
},   

fix:
"osx": {
					"program": "./bin/osx/ravidebug"
},

**Comment by dibyendumajumdar** [comment]
Hi thanks for reporting this. May I know which version of VS Code had an issue?

**Comment by 10der** [comment]
June 2018 (version 1.25)
Update 1.25.1: The update addresses these issues.

**Comment by dibyendumajumdar** [comment]
So VS Code broke something? It isn't the first time.

**Comment by 10der** [comment]
M$ 
¯\\_(ツ)_/¯
