### ISSUE TITLE
Open source, sometime? 

### ISSUE THREAD

**Issue by dhayhak** [dibyendumajumdar/ravi-vscode-debugger#3]
👋 

Congratulation on the great extension! Excellent work!
I'm wondering if you have plans to open/share the source code

Thanks!

**Comment by dibyendumajumdar** [comment]
Hi, thanks. Interested to know which platform you tried it on. It's already opensource, code is in the Ravi project repo. Please see https://github.com/dibyendumajumdar/ravi/tree/master/vscode-debugger. Note that the debugger adapter is part of the Ravi VM; not usable as a generic adapter for Lua.

**Comment by dhayhak** [comment]
Thanks for pointing out the ravi repo. I tried it on MacOS.
