### ISSUE TITLE
unable to set breakpoint

### ISSUE THREAD

**Issue by frozen-eye** [dibyendumajumdar/ravi-vscode-debugger#4]
ext version: 0.0.28
vscode 1.53.2
windows 10
remote ssh

**Comment by dibyendumajumdar** [comment]
Hi @frozen-eye - sorry for some reason I missed your issue. I too found the breakpoints cannot be set.

Cause: https://github.com/microsoft/vscode/issues/129361#event-5068374579

I will upload a fix

**Comment by dibyendumajumdar** [comment]
I updated the package to the new package.json format for breakpoints so hopefully this is now fixed.

**Comment by frozen-eye** [comment]
Thanks! Breakpoints can be set now!
